### ISSUE TITLE
Site doesn't redirect automatically to HTTPS. 

### ISSUE THREAD

**Issue by eliseomartelli** [tsi-unito/tsi-unito.github.io#1]
Site doesn't automatically redirect to HTTPS. See GitHub's docs [0]. 

This issue might break the site on some browser expecting HTTPS-only pages.

[0] https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

**Comment by federicotorrielli** [comment]
Fixato, grazie mille!
